plugins:
  # - jest
  - babel

env:
  node: true
  browser: true
  es2021: true
  # jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  # - 'plugin:jest/recommended'

rules: 
  no-console: 0
  import/export: 0
